### ISSUE TITLE
how to transfer data between psdk and msdk?

### ISSUE THREAD

**Issue by Aspirinkb** [umdlife/psdk_ros2#102]
Does psdk-ros2 support transfer custom message data between psdk and msdk?      

I have developed a ros2 node to:   
1. receive data from msdk, and then publish the data to other topics;
2. send data, which subscribed from other topic, to msdk;   

How can I run the node and the psdk-ros2 package at the same time?   

If not, is there another way to implement the function?

**Comment by vicmassy** [comment]
This is out of the scope of this repository. Address this questions to DJI itself. This repository is only regarding the PSDK wrapper in ROS2 not the MSDK.  
Also other ROS2 generic questions address the forums of ROS2. 

I would recommend you go through some of the [ROS2 tutorials](https://docs.ros.org/en/humble/Tutorials.html) to get a basic knowledge of how ROS2 works.
