### ISSUE TITLE
Compatible Connections

### ISSUE THREAD

**Issue by andre-f-moura** [umdlife/psdk_ros2#14]
Hello,

First of all, thank you for developing this wrapper. I was trying to do some similar interface for ROS1 and was considering doing it for ROS 2 also, but now I'll probably use this one for ROS 2.

What connections are you considering for this wrapper? I'm using the DJI E-Port Dev Kit on a M350 RTK. For my ROS 1 wrapper I used the UART pins on the dev kit and a USB A OTG to USB-C connection, in network mode, both connected to an Nvidia Jetson during my tests.
What are suppose to be the hardware connections behind "/dev/dji_serial" and "/dev/dji_advanced_sensing" in this case? How can I use the two UART connections?

Thank you!

**Comment by biancabnd** [comment]
Hi @andre-f-moura,

Thank you for your interest in the wrapper.
As the documentation mentions, we have mainly tested this wrapper using a M300 RTK. How we do the connection to this drone is via the OSDK expansion module. The two hardware connections you mention `dji_serial` and `dji_advanced_sensing` are the two USB (serial) communication we get from the OSDK module which we connect to our board. 

We have never used the E-Port Dev Kit, but I would assume that you need to change the hardware_connection parameter in the `psdk_params.yaml.` As you see, now we have it hardcoded to the `DJI_USE_UART_AND_USB_BULK_DEVICE` which works for the connection with the OSDK module, but I guess it is not the same if you connect via the E-Port. The connection method should be the same as the one you use when you run the psdk samples (if you have done that already with your set-up). 

Please let us know any findings you obtain.
