### ISSUE TITLE
Declare parameter data_frequency.altitude

### ISSUE THREAD

**Issue by Janphr** [umdlife/psdk_ros2#36]
Hey,

thanks for all the work!
You're not declaring the new parameter data_frequency.altitude [here](https://github.com/umdlife/psdk_ros2/blob/df932a6f1fe1dead74ca5c8f94ece3d7d79e1b2c/psdk_wrapper/src/psdk_wrapper.cpp#L52)
Throws: `[psdk_wrapper_node-1] [ERROR] [1704814450.520272733] [wrapper.psdk_wrapper_node]: altitude frequency param not defined`
Fix: Add line
```
declare_parameter("data_frequency.altitude", 1);
```

Best regards!

**Comment by biancabnd** [comment]
Hi @Janphr, 
Thanks for reporting it. It is being fixed in https://github.com/umdlife/psdk_ros2/pull/37 and will get merged asap.
