### ISSUE TITLE
High Speed Data Channel

### ISSUE THREAD

**Issue by Yamboy1** [umdlife/psdk_ros2#39]
Is there a way to control the [data transmission channels](https://developer.dji.com/doc/payload-sdk-tutorial/en/function-set/basic-function/data-transmission.html) using this library?

**Comment by biancabnd** [comment]
Hi @Yamboy1, 
As this wrapper is built on top the native Payload SDK of DJI it is technically possible to do that. However, at this moment this feature is not implemented in the ros2 wrapper. We encourage you to open a PR with this implementation or even adding more details on how this could be added to the wrapper and what benefits it would bring.
