### ISSUE TITLE
psdk wrapper in ros index

### ISSUE THREAD

**Issue by santiago-tapia** [umdlife/psdk_ros2#40]
Hi there,

We are using your wrapper to integrate PSDK into our developments. So, we are interested in your plans about a future deployment using the ROS index. 

I suppose the main difficulty in doing so is the original PSDK library, because only the binaries are available. So, my questions are:

Are you planning to use the ROS Index to deliver the PSDK Wrapper? 
What is your opinion about the dependency on the PSDK library? 

I have reviewed the https://github.com/dji-sdk/Payload-SDK/blob/master/LICENSE.txt and it has an strange issue: it is a very permissive MIT licence, so basically it could be used without no real restriction (and the license literally includes the binary file, that is all lib*.a files), but there are no source files, therefore we might include them in a public debian package repository as long as the procedure to produce that inclusion do not require to compile the code. It might be a candidate for being at the ROS Index _system_ dependencies.   
 
Best,

    Santiago

**Comment by vicmassy** [comment]
Hey @santiago-tapia, 

Happy to see that you use the library for your development. :1st_place_medal: 

The plan for the PSDK Wrapper is to release it in the ROS index so it can be installed with the package manager. We started the process of the release today and hopefully in the upcoming weeks it gets sorted out and you can enjoy the wrapper using `sudo apt install ros-humble-psdk-wrapper`. 

In parallel we are evaluating how to handle the PSDK library as a dependency as well as the legal terms and implications. Will keep you posted on that.

In the meantime, you can get the debian packages in the [release](https://github.com/umdlife/psdk_ros2/releases) files of the Github repository. For now we build for `amd64` and `arm64`.

**Comment by santiago-tapia** [comment]
Hi @vicmassy ,

Great, we are looking forward to hear about your news.

Best,

    Santiago

**Comment by vicmassy** [comment]
Hi @santiago-tapia, 
I am happy to inform that we completed all the procedure for submitting the package to the ROS index. We completed the release process and you can track the progress [here](https://github.com/ros/rosdistro/pull/39744). Its only pending the merge of this PR, and then the sync for Humble. 

A major thing to notice is that now you do not need to have the Payload-SDK as a source since we do take care of it internally in the CMake of the wrapper. Version 0.0.4 will be the first one to be released in the ROS Index so be sure to check it out

**Comment by santiago-tapia** [comment]
Hi @vicmassy 

Those are very good news. We will use it as soon as we can. 

Thanks indeed,

    Santiago

**Comment by vicmassy** [comment]
@santiago-tapia the debians are finally released in the ROS2 index under the latest update of Humble
