### ISSUE TITLE
The node cannot be reconnected to the drone after the node is killed

### ISSUE THREAD

**Issue by RPS98** [umdlife/psdk_ros2#78]
**Tell us about your environment**

* **Ubuntu version: 22.04**
* **Docker Version:**
* **ROS/ROS2 version: ROS 2 Humble**
* **Commit hash: main 94cfd3a71a9419b4a9b030a439253c7ff6f6ebca**

#### Steps to reproduce issue

1. Launch PSDK wrapper and wait for connection
2. Kill the node using SIGINT (Ctrl+C)
3. Relaunch the PSDK wrapper and observe that the connection fails, as the DJI Core cannot be initialized

#### Expected behavior

Being able to reconnect to the drone without rebooting it.

#### Actual behavior

I must reboot the drone after each connection.

#### Are you willing to make a PR? If yes, add the PR link here.
I found a solution by calling the DJI Core and module `Deinit` functions in PR  #77

**Comment by biancabnd** [comment]
Closing this as the PR has been merged!
